In [1]:
import numpy as np 
import pandas as pd

In [2]:
xlsx = pd.ExcelFile('Accuracy and Coverage.xlsx')
lang_df = pd.read_excel(xlsx, 'Accuracy')
lang_df.set_index(lang_df.iloc[:,0])
lang_df.drop(columns=['src/tgt'])
print(lang_df)
lang_mat = lang_df.values
print(lang_mat)
lang_mat = np.delete(lang_mat,0,1)
print(lang_mat)

  src/tgt      en      tr      de      fi      fr      hr      it      ru
0      en  1.0000  0.2469  0.3404  0.2375  0.5828  0.2135  0.5511  0.2142
1      tr  0.2469  1.0000  0.2100  0.1611  0.3026  0.1575  0.2946  0.1038
2      de  0.3404  0.2100  1.0000  0.2298  0.3272  0.2112  0.3420  0.1540
3      fi  0.2375  0.1611  0.2298  1.0000  0.3284  0.2534  0.3210  0.2839
4      fr  0.5828  0.3026  0.3272  0.3284  1.0000  0.3210  0.6410  0.4332
5      hr  0.2135  0.1575  0.2112  0.2534  0.3611  1.0000  0.3687  0.3252
6      it  0.5511  0.2946  0.3420  0.3210  0.6410  0.3687  1.0000  0.4293
7      ru  0.2142  0.1038  0.1540  0.2839  0.4332  0.3252  0.4293  1.0000
[['en' 1.0 0.2469 0.3404 0.2375 0.5828 0.2135 0.5511 0.2142]
 ['tr' 0.2469 1.0 0.21 0.1611 0.3026 0.1575 0.2946 0.1038]
 ['de' 0.3404 0.21 1.0 0.2298 0.3272 0.2112 0.342 0.154]
 ['fi' 0.2375 0.1611 0.2298 1.0 0.3284 0.2534 0.321 0.2839]
 ['fr' 0.5828 0.3026 0.3272 0.3284 1.0 0.321 0.641 0.4332]
 ['hr' 0.2135 0.1575 0.2112 0.2534 0.3

In [3]:
#A = np.array([[1, 0.1, 0.8],[0,1,0.3],[0.9,0.99,1]])

#print("\n\nA:\n\n")
#print(A)

A = lang_mat

In [8]:
#names = [_ for _ in 'abc']
#df = pd.DataFrame(A, index=names, columns=names)
#print("\n\nDF:\n\n")
#print(df)
#print("\n\nnames:\n\n")
#print(names)
names = ['en','tr','de','fi','fr','hr','it','ru']
df = pd.DataFrame(A, index=names, columns=names)

[[1.0 0.2469 0.3404 0.2375 0.5828 0.2135 0.5511 0.2142]
 [0.2469 1.0 0.21 0.1611 0.3026 0.1575 0.2946 0.1038]
 [0.3404 0.21 1.0 0.2298 0.3272 0.2112 0.342 0.154]
 [0.2375 0.1611 0.2298 1.0 0.3284 0.2534 0.321 0.2839]
 [0.5828 0.3026 0.3272 0.3284 1.0 0.321 0.641 0.4332]
 [0.2135 0.1575 0.2112 0.2534 0.3611 1.0 0.3687 0.3252]
 [0.5511 0.2946 0.342 0.321 0.641 0.3687 1.0 0.4293]
 [0.2142 0.1038 0.154 0.2839 0.4332 0.3252 0.4293 1.0]]


In [5]:
lang_dict = {
    0: "en",
    1: "tr",
    2: "de",
    3: "fi",
    4: "fr",
    5: "hr",
    6: "it",
    7: "ru"
}

In [6]:
accuracy = []
source = []
target = []
pivot = []
og_accuracy = []
for src_lang in range(0,len(df)):
    for tgt_lang in range(0,len(df)):
        for pvt_lang in range(0,len(df)):
            og_accuracy.append(A[src_lang,tgt_lang])
for src_lang in range(0, len(df)):
    for tgt_lang in range(0, len(df)):
        for pvt_lang in range(0, len(df)):
            source.append(lang_dict[src_lang]) #FEEDING INTO THE DICTIONARY WHEN APPENDING INTO THE DF
            target.append(lang_dict[tgt_lang]) #FEEDING INTO THE DICTIONARY WHEN APPENDING INTO THE DF
            pivot.append(lang_dict[pvt_lang]) #FEEDING INTO THE DICTIONARY WHEN APPENDING INTO THE DF
            accuracy.append("{:.3f}".format(A[src_lang,pvt_lang]*A[pvt_lang,tgt_lang])) #ALWAYS PRINT TO 3 DECIMAL PLACES CAUSE IT WAS BUGGING OUT
print(source)
print("\n\nlength of source:\n\n")
print(len(source))
print("\n\nlength of target:\n\n")
print(len(target))
print("\n\nlength of pivot:\n\n")
print(len(pivot))
print("\n\nlength of accuracy:\n\n")
print(len(accuracy))
print("\n\nlength of og_accuracy:\n\n")
print(len(og_accuracy))

['en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'en', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'tr', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de', 'de

In [7]:
newdf_data = np.array([source,target,pivot,accuracy,og_accuracy])
newdf_data = newdf_data.transpose()
newdf = pd.DataFrame(newdf_data, columns=['source','target','pivot','accuracy','original'])
newdf = newdf[(newdf.source != newdf.target) & (newdf['source'] != newdf['pivot']) & (newdf['target'] != newdf['pivot'])]

#rename
print("\n\nnewdf:\n\n")
print(newdf)

#Select only where pivot is better
print("\n\nbetter pivot newdf:\n\n")
print(newdf[newdf['accuracy'] >= newdf['original']])



newdf:


    source target pivot accuracy original
10      en     tr    de    0.071   0.2469
11      en     tr    fi    0.038   0.2469
12      en     tr    fr    0.176   0.2469
13      en     tr    hr    0.034   0.2469
14      en     tr    it    0.162   0.2469
..     ...    ...   ...      ...      ...
497     ru     it    tr    0.031   0.4293
498     ru     it    de    0.053   0.4293
499     ru     it    fi    0.091   0.4293
500     ru     it    fr    0.278   0.4293
501     ru     it    hr    0.120   0.4293

[336 rows x 5 columns]


better pivot newdf:


    source target pivot accuracy original
60      en     ru    fr    0.252   0.2142
62      en     ru    it    0.237   0.2142
124     tr     ru    fr    0.131   0.1038
126     tr     ru    it    0.126   0.1038
452     ru     en    fr    0.252   0.2142
454     ru     en    it    0.237   0.2142
460     ru     tr    fr    0.131   0.1038
462     ru     tr    it    0.126   0.1038
